/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET
 * 让 .NET 开发更简单、更通用、更流行。前后端分离架构(.NET6/Vue3)，开箱即用紧随前沿技术。<br/><a href='https://gitee.com/zuohuaijun/Admin.NET/'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 515096995@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 博客类型枚举<br />&nbsp;未知 None = 0<br />&nbsp;转发 Forward = 1<br />&nbsp;原创 Original = 2<br />
 * &nbsp;翻译 Translate = 3<br />
 * @export
 * @enum {string}
 */
 export enum BlogTypeEnum {
    None = 0,
    Forward = 1,
    Original = 2,
    Translate = 3
}
/**
 * 博客状态枚举<br />&nbsp;草稿 Draft = 0<br />&nbsp;已发布 Publish = 1<br />
 * @export
 * @enum {string}
 */
 export enum BlogStatusEnum {
    Draft = 0,
    Publish = 1
}
